import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { Admin, CustomRoutes, Layout, Menu, Resource, type DataProvider, type RaRecord } from 'react-admin';
import { Route, Link, useNavigate, useParams } from 'react-router-dom';
import {
  Alert, AppBar, Box, Button, Card, CardActions, CardContent, Chip, CircularProgress,
  Dialog, DialogActions, DialogContent, DialogTitle, Divider, FormControl, InputLabel,
  LinearProgress, MenuItem, Select, Stack, Step, StepLabel, Stepper, Tab, Tabs, GlobalStyles,
  TextField, Toolbar, Typography,
} from '@mui/material';
import DashboardIcon from '@mui/icons-material/Dashboard';
import SettingsIcon from '@mui/icons-material/Settings';
import { api, mutationHeaders, streamProject, type Stage, type Workflow } from './api';
import { useQueryClient } from '@tanstack/react-query';

const i18nProvider = {
  translate: (key: string, options?: { _: string }) => (({ 'ra.navigation.skip_nav': 'К содержимому', 'ra.page.dashboard': 'Главная', 'ra.action.refresh': 'Обновить' } as Record<string, string>)[key] || options?._ || key),
  changeLocale: async (locale: string) => { localStorage.setItem('workspace-locale', locale); },
  getLocale: () => localStorage.getItem('workspace-locale') || 'ru',
};

const resources = ['projects', 'connections', 'agents', 'prompts', 'runs', 'approvals', 'artifacts'] as const;
const dataProvider = {
  getList: async resource => {
    const data = await api<RaRecord[]>(`/${resource}`);
    return { data, total: data.length };
  },
  getOne: async (resource, params) => ({ data: await api<RaRecord>(`/${resource}/${params.id}`) }),
  create: async (resource, params) => ({ data: await api<RaRecord>(`/${resource}`, { method: 'POST', body: JSON.stringify({ data: params.data }) }) }),
  update: async (resource, params) => ({ data: await api<RaRecord>(`/${resource}/${params.id}`, { method: 'PUT', body: JSON.stringify({ data: params.data }) }) }),
  delete: async (resource, params) => ({ data: await api<RaRecord>(`/${resource}/${params.id}`, { method: 'DELETE' }) }),
  getMany: async (resource, params) => ({ data: await Promise.all(params.ids.map(id => api<RaRecord>(`/${resource}/${id}`))) }),
  getManyReference: async () => ({ data: [], total: 0 }), updateMany: async () => ({ data: [] }), deleteMany: async () => ({ data: [] }),
} as DataProvider;

function ProjectMenu() {
  return <Menu><Menu.DashboardItem /><Menu.Item to="/projects" primaryText="Проекты" leftIcon={<DashboardIcon />} /><Menu.Item to="/connections" primaryText="Подключения" leftIcon={<SettingsIcon />} /><Menu.Item to="/agents" primaryText="Агенты" leftIcon={<SettingsIcon />} /><Menu.Item to="/approvals" primaryText="Решения" leftIcon={<SettingsIcon />} /><Menu.Item to="/runs" primaryText="Запуски" leftIcon={<SettingsIcon />} /></Menu>;
}

function WorkspaceLayout(props: any) { return <Layout {...props} menu={ProjectMenu} />; }

type DirectoryListing = { current: string; parent: string | null; directories: { name: string; path: string }[] };

export function Home() {
  const [projects, setProjects] = useState<RaRecord[]>([]);
  const [error, setError] = useState(''); const [open, setOpen] = useState(false); const [pickerOpen, setPickerOpen] = useState(false); const [listing, setListing] = useState<DirectoryListing>(); const [name, setName] = useState(''); const [root, setRoot] = useState(''); const navigate = useNavigate();
  useEffect(() => { api<RaRecord[]>('/projects').then(setProjects).catch(e => setError(String(e.message))); }, []);
  const browse = async (path = root) => { try { setListing(await api<DirectoryListing>(`/filesystem/directories${path ? `?path=${encodeURIComponent(path)}` : ''}`)); setPickerOpen(true); } catch (e) { setError((e as Error).message); } };
  return <Box p={3}><Typography variant="h4" gutterBottom>Управляемое исследование 1С</Typography>
    <Typography color="text.secondary" mb={3}>Настройка, выполнение, контроль и результаты — без командной строки.</Typography>
    <Button variant="contained" onClick={() => setOpen(true)} sx={{ mb: 3 }}>Создать или открыть проект</Button>
    {error && <Alert severity="error">{error}</Alert>}
    <Stack spacing={2}>{projects.map(project => <Card key={project.id}><CardContent><Typography variant="h6">{String(project.name)}</Typography><Typography component="code">{String(project.root)}</Typography></CardContent><CardActions><Button component={Link} to={`/projects/${project.id}/workflow`}>Открыть процесс</Button><Button component={Link} to={`/projects/${project.id}/setup`}>Настройка</Button></CardActions></Card>)}</Stack>
    <Dialog open={open} onClose={() => setOpen(false)}><DialogTitle>Создать или открыть проект</DialogTitle><DialogContent><Stack spacing={2} sx={{ mt: 1, minWidth: { sm: 480 } }}><TextField label="Название" required value={name} onChange={e => setName(e.target.value)} /><Stack direction="row" spacing={1} alignItems="flex-start"><TextField fullWidth label="Папка проекта" required value={root} onChange={e => setRoot(e.target.value)} helperText="В папке должен находиться project.toml; новые репозитории создаются штатным шаблоном сервера." /><Button variant="outlined" onClick={() => browse()} sx={{ mt: 1 }}>Выбрать</Button></Stack></Stack></DialogContent><DialogActions><Button onClick={() => setOpen(false)}>Отмена</Button><Button variant="contained" onClick={async () => { try { const item = await api<RaRecord>('/projects', { method: 'POST', body: JSON.stringify({ name, root }) }); navigate(`/projects/${item.id}/setup`); } catch (e) { setError((e as Error).message); setOpen(false); } }}>Продолжить</Button></DialogActions></Dialog>
    <Dialog open={pickerOpen} onClose={() => setPickerOpen(false)} fullWidth maxWidth="sm"><DialogTitle>Выберите папку проекта</DialogTitle><DialogContent><Typography variant="caption">Текущая папка</Typography><Typography component="code" sx={{ display: 'block', mb: 1, overflowWrap: 'anywhere' }}>{listing?.current}</Typography><Typography color="text.secondary" variant="body2" mb={1}>{listing?.parent ? 'Нажмите на папку, чтобы открыть её.' : 'Это граница разрешённой области. Выше перейти нельзя.'}</Typography><Button disabled={!listing?.parent} onClick={() => listing?.parent && browse(listing.parent)} sx={{ justifyContent: 'flex-start' }}>← Назад</Button><Divider /><Stack>{listing?.directories.map(directory => <Button key={directory.path} onClick={() => browse(directory.path)} sx={{ justifyContent: 'flex-start' }}>📁 {directory.name}</Button>)}</Stack></DialogContent><DialogActions><Button onClick={() => setPickerOpen(false)}>Отмена</Button><Button variant="contained" onClick={() => { if (listing) setRoot(listing.current); setPickerOpen(false); }}>Выбрать эту папку</Button></DialogActions></Dialog>
  </Box>;
}

const wizardSteps = ['Проект', 'Информационные базы', 'Исходники', 'Политика доступа', 'Проверки', 'Этапы и агенты'];
type Setup = { step?: number; product?: string; version?: string; source_roles?: string; infobases?: string; vendor_connection?: string; customer_connection?: string; next_vendor_connection?: string; read_only?: boolean; checked?: boolean; enabled_stages?: string; agent_assignments?: string; complete?: boolean };

export function SetupWizard() {
  const { projectId = '' } = useParams(); const navigate = useNavigate();
  const [project, setProject] = useState<Workflow['project']>(); const [setup, setSetup] = useState<Setup>({ read_only: true });
  const [connections, setConnections] = useState<RaRecord[]>([]);
  const [step, setStep] = useState(0); const [error, setError] = useState(''); const [fieldErrors, setFieldErrors] = useState<Record<string, string>>({}); const [manifestPreview, setManifestPreview] = useState<{ diff: string; updates: Record<string, Record<string, unknown>> }>(); const [saving, setSaving] = useState(false);
  useEffect(() => { Promise.all([api<Workflow['project']>(`/projects/${projectId}`), api<RaRecord[]>('/connections')]).then(([value, available]) => { setProject(value); setConnections(available); const saved = value.setup as Setup; setSetup(saved); setStep(Number(saved.step || 0)); }).catch(e => setError(e.message)); }, [projectId]);
  const save = async (nextStep: number, complete = false) => {
    setSaving(true); setError(''); setFieldErrors({}); const ids = [setup.vendor_connection, setup.customer_connection, setup.next_vendor_connection].filter(Boolean); const value = { ...setup, infobases: JSON.stringify(ids), step: nextStep, complete };
    try { if (complete) { if (!manifestPreview || !project) throw new Error('Сначала проверьте изменения project.toml'); await api(`/projects/${projectId}/manifest`, { method: 'PUT', body: JSON.stringify({ expected_hash: project.manifest_hash, updates: manifestPreview.updates }) }); } const saved = await api<Workflow['project']>(`/projects/${projectId}/setup`, { method: 'PUT', body: JSON.stringify(value) }); setSetup(saved.setup as Setup); setStep(nextStep); if (complete) navigate(`/projects/${projectId}/workflow`); } catch (e) { const message = (e as Error).message; setError(message); try { setFieldErrors(JSON.parse(message).fields || {}); } catch { /* typed server detail is optional */ } } finally { setSaving(false); }
  };
  const previewManifest = async () => { try { if (!project) return; const sources = JSON.parse(String(setup.source_roles || '{}')); const updates = { project: { product: setup.product || '', target_version: setup.version || '' }, paths: sources }; const preview = await api<{ diff: string }>(`/projects/${projectId}/manifest/preview`, { method: 'POST', body: JSON.stringify({ expected_hash: project.manifest_hash, updates }) }); setManifestPreview({ diff: preview.diff, updates }); } catch (e) { setError((e as Error).message); } };
  const inspect = async () => { setSaving(true); setError(''); try { const result = await api<{ ok: boolean; doctor: { summary: { fail: number; warn: number } }; tested_connections: number }>(`/projects/${projectId}/inspect`, { method: 'POST' }); setSetup({ ...setup, checked: result.ok }); if (!result.ok) setError(`Проверки не пройдены: ошибок ${result.doctor.summary.fail}, проверенных подключений ${result.tested_connections}`); } catch (e) { setSetup({ ...setup, checked: false }); setError((e as Error).message); } finally { setSaving(false); } };
  const field = (key: keyof Setup, label: string, required = true) => <TextField fullWidth required={required} label={label} value={String(setup[key] ?? '')} error={Boolean(fieldErrors[key])} helperText={fieldErrors[key]} onChange={e => setSetup({ ...setup, [key]: e.target.value })} />;
  return <Box p={3} maxWidth={960} mx="auto"><Typography variant="h4">Первоначальная настройка</Typography><Typography color="text.secondary" mb={3}>{project?.name}</Typography>
    <Stepper activeStep={step} alternativeLabel sx={{ mb: 4 }}>{wizardSteps.map(label => <Step key={label}><StepLabel>{label}</StepLabel></Step>)}</Stepper>
    {error && <Alert severity="error" sx={{ mb: 2 }}>{error}</Alert>}
    <Card><CardContent><Stack spacing={2}>
      {step === 0 && <>{field('product', 'Продукт')}{field('version', 'Версия')}</>}
      {step === 1 && <><TextField select required label="База поставщика" value={setup.vendor_connection || ''} onChange={e => setSetup({ ...setup, vendor_connection: e.target.value })}>{connections.map(item => <MenuItem key={item.id} value={String(item.id)}>{String(item.name)}</MenuItem>)}</TextField><TextField select required label="База заказчика" value={setup.customer_connection || ''} onChange={e => setSetup({ ...setup, customer_connection: e.target.value })}>{connections.map(item => <MenuItem key={item.id} value={String(item.id)}>{String(item.name)}</MenuItem>)}</TextField><TextField select label="Следующая версия поставщика" value={setup.next_vendor_connection || ''} onChange={e => setSetup({ ...setup, next_vendor_connection: e.target.value })}><MenuItem value="">Не использовать</MenuItem>{connections.map(item => <MenuItem key={item.id} value={String(item.id)}>{String(item.name)}</MenuItem>)}</TextField><Button component={Link} to="/connections">Управлять подключениями</Button></>}
      {step === 2 && <><Alert severity="info">Исходники будут выгружены управляемым этапом процесса в каталоги шаблона.</Alert>{Object.entries(JSON.parse(setup.source_roles || '{}')).map(([role, path]) => <Typography key={role}><code>{role}</code> → <code>{String(path)}</code></Typography>)}</>}
      {step === 3 && <TextField select label="Доступ" value={setup.read_only ? 'read' : 'write'} onChange={e => setSetup({ ...setup, read_only: e.target.value === 'read' })}><MenuItem value="read">Только чтение</MenuItem><MenuItem value="write">Запись с подтверждением каждого запуска</MenuItem></TextField>}
      {step === 4 && <><Alert severity={setup.checked ? 'success' : 'info'}>{setup.checked ? 'Пути, проект и подключения проверены сервером' : 'Запустите проверку путей, проекта и подключений перед продолжением.'}</Alert><Button variant="outlined" disabled={saving} onClick={inspect}>{saving ? 'Проверка…' : 'Запустить проверки'}</Button></>}
      {step === 5 && <>{field('enabled_stages', 'Включенные этапы (через запятую)')}{field('agent_assignments', 'Назначения агентов (JSON)', false)}<Button variant="outlined" onClick={previewManifest}>Предпросмотр project.toml</Button>{manifestPreview && <Box component="pre" aria-label="Изменения project.toml" sx={{ whiteSpace: 'pre-wrap', overflow: 'auto' }}>{manifestPreview.diff || 'Изменений нет'}</Box>}</>}
    </Stack></CardContent><CardActions sx={{ justifyContent: 'space-between' }}><Button disabled={step === 0 || saving} onClick={() => save(step - 1)}>Назад</Button><Button variant="contained" disabled={saving || (step === 4 && !setup.checked) || (step === wizardSteps.length - 1 && !manifestPreview)} onClick={() => save(Math.min(step + 1, wizardSteps.length - 1), step === wizardSteps.length - 1)}>{saving ? 'Сохранение…' : step === wizardSteps.length - 1 ? 'Применить и завершить' : 'Сохранить и продолжить'}</Button></CardActions></Card>
  </Box>;
}

const statusColor = (status: string): 'default' | 'success' | 'error' | 'warning' | 'info' => ({ completed: 'success', failed: 'error', interrupted: 'warning', running: 'info' }[status] as never || 'default');

export function WorkflowPage() {
  const { projectId = '' } = useParams(); const [value, setValue] = useState<Workflow>(); const [online, setOnline] = useState(true); const [error, setError] = useState('');
  const queryClient = useQueryClient();
  const refresh = useCallback(() => api<Workflow>(`/projects/${projectId}/workflow`).then(setValue).catch(e => setError(e.message)), [projectId]);
  useEffect(() => { refresh(); const stop = streamProject(projectId, event => { queryClient.invalidateQueries({ queryKey: ['workflow', projectId] }); const payload = JSON.parse(event.data || '{}'); if (payload.run_id) queryClient.invalidateQueries({ queryKey: ['runs', payload.run_id] }); refresh(); }, setOnline); const timer = window.setInterval(refresh, online ? 30000 : 5000); return () => { stop(); clearInterval(timer); }; }, [projectId, queryClient, refresh, online]);
  if (!value) return <Box p={4}>{error ? <Alert severity="error">{error}</Alert> : <CircularProgress />}</Box>;
  const done = value.stages.filter(s => s.status === 'completed').length;
  return <Box p={3}><Stack direction={{ xs: 'column', md: 'row' }} justifyContent="space-between" mb={2}><Box><Typography variant="h4">{value.project.name}</Typography><Typography color="text.secondary">{value.project.root}</Typography></Box><Chip color={online ? 'success' : 'warning'} label={online ? 'Обновления в реальном времени' : 'Режим периодического опроса'} /></Stack>
    <Typography aria-live="polite" position="absolute" sx={{ width: 1, height: 1, overflow: 'hidden', clip: 'rect(0 0 0 0)' }}>Завершено {done} из {value.stages.length}</Typography><LinearProgress variant="determinate" value={100 * done / value.stages.length} aria-label={`Завершено ${done} из ${value.stages.length}`} sx={{ mb: 3 }} />
    <Box display="grid" gridTemplateColumns="repeat(auto-fit,minmax(300px,1fr))" gap={2}>{value.stages.map(stage => <StageCard key={stage.id} projectId={projectId} stage={stage} onRun={refresh} />)}</Box>
  </Box>;
}

function StageCard({ projectId, stage, onRun }: { projectId: string; stage: Stage; onRun: () => void }) {
  const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const run = async () => { setBusy(true); setError(''); try { await api('/runs', { method: 'POST', headers: mutationHeaders(), body: JSON.stringify({ project_id: projectId, stage_id: stage.id, payload: {} }) }); onRun(); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } };
  return <Card id={`stage-${stage.id}`} variant="outlined"><CardContent><Stack direction="row" justifyContent="space-between"><Typography variant="h6">{stage.title}</Typography><Chip size="small" color={statusColor(stage.status)} label={stage.status} /></Stack><Typography variant="caption">{stage.kind === 'agent' ? 'Агентский этап' : 'Детерминированный этап'}</Typography>{stage.blockers.length > 0 && <Alert severity="warning" sx={{ mt: 2 }}>Требуются: {stage.blockers.join(', ')}</Alert>}{error && <Alert severity="error" sx={{ mt: 2 }}>{error}</Alert>}</CardContent><CardActions><Button component={Link} to={`/projects/${projectId}/stages/${stage.id}`}>Подробнее</Button>{stage.kind === 'agent' ? <Button component={Link} to={`/projects/${projectId}/stages/${stage.id}`} disabled={!stage.ready}>Настроить и запустить</Button> : <Button onClick={run} disabled={!stage.ready || busy || ['queued', 'running'].includes(stage.status)}>Запустить</Button>}{stage.artifact && <Button component="a" href={`/api/v1/artifacts/${projectId}/${stage.artifact}?embed=true`} target="_blank">Результат</Button>}</CardActions></Card>;
}

type DiscoveredInfobase = { name: string; connection_string: string; connection_kind: string; server: string; reference: string; file: string; folder: string; platform_version: string; credentials_ignored: boolean };

function ConnectionCredentials({ item, onSaved, onError }: { item: RaRecord; onSaved: () => void; onError: (message: string) => void }) {
  const [open, setOpen] = useState(false); const [username, setUsername] = useState(String(item.user || '')); const [secret, setSecret] = useState(''); const channel = String(item.channel);
  const passwordLabel = channel === 'onec' ? 'Пароль пользователя 1С' : channel === 'postgresql' ? 'Пароль PostgreSQL' : 'Токен доступа';
  const save = async () => { try { await api(`/connections/${item.id}/credentials`, { method: 'PUT', body: JSON.stringify({ username, secret }) }); setSecret(''); onSaved(); } catch (e) { onError((e as Error).message); } };
  return <Stack spacing={1}><Button onClick={() => setOpen(value => !value)}>{open ? 'Скрыть настройки доступа' : 'Настроить доступ'}</Button>{open && <>{['onec', 'postgresql'].includes(channel) && <TextField label={channel === 'onec' ? 'Пользователь 1С' : 'Пользователь PostgreSQL'} value={username} onChange={e => setUsername(e.target.value)} />}{item.secret_present && <Alert severity="success">Секрет сохранён</Alert>}<TextField label={passwordLabel} type="password" value={secret} onChange={e => setSecret(e.target.value)} autoComplete="new-password" /><Button variant="outlined" disabled={!secret} onClick={save}>Сохранить доступ</Button></>}</Stack>;
}

function ConnectionsPage() {
  const [items, setItems] = useState<RaRecord[]>([]); const [error, setError] = useState(''); const [createOpen, setCreateOpen] = useState(false); const [discovered, setDiscovered] = useState<DiscoveredInfobase[]>([]); const [discoveryOpen, setDiscoveryOpen] = useState(false); const [discoverySource, setDiscoverySource] = useState('');
  const [form, setForm] = useState({ name: '', role: 'customer', channel: 'mcp', url: '', connection_string: '', platform_version: '8.3.27.1989' });
  const refresh = useCallback(() => api<RaRecord[]>('/connections').then(setItems).catch(e => setError(e.message)), []); useEffect(() => { refresh(); }, [refresh]);
  const discover = async () => { try { const result = await api<{ source: string; infobases: DiscoveredInfobase[] }>('/infobases/discover'); setDiscovered(result.infobases); setDiscoverySource(result.source); setDiscoveryOpen(true); } catch (e) { setError((e as Error).message); } };
  const importInfobase = async (item: DiscoveredInfobase) => { try { await api('/connections', { method: 'POST', body: JSON.stringify({ data: { ...item, role: 'customer', channel: 'onec', access_mode: 'read' } }) }); setDiscoveryOpen(false); refresh(); } catch (e) { setError((e as Error).message); } };
  const create = async () => { try { await api('/connections', { method: 'POST', body: JSON.stringify({ data: { ...form, access_mode: 'read' } }) }); setCreateOpen(false); refresh(); } catch (e) { setError((e as Error).message); } };
  const remove = async (item: RaRecord) => { if (!window.confirm(`Удалить подключение «${String(item.name)}»?`)) return; try { await api(`/connections/${item.id}`, { method: 'DELETE' }); refresh(); } catch (e) { setError((e as Error).message); } };
  const target = (item: RaRecord) => item.channel === 'onec' ? (item.connection_kind === 'server' ? `${String(item.server)} / ${String(item.reference)}` : String(item.file || item.connection_string)) : String(item.url || 'Адрес не указан');
  return <Box p={3}><Typography variant="h4" mb={2}>Подключения к ИБ</Typography>{error && <Alert severity="error" sx={{ mb: 2 }}>{error}</Alert>}<Stack direction={{ xs: 'column', sm: 'row' }} spacing={1} mb={3}><Button variant="contained" onClick={discover}>Найти базы 1С</Button><Button variant="outlined" onClick={() => setCreateOpen(true)}>Добавить вручную</Button></Stack><Box display="grid" gridTemplateColumns="repeat(auto-fit,minmax(340px,1fr))" gap={2}>{items.map(item => <Card key={item.id} variant="outlined"><CardContent><Stack direction="row" justifyContent="space-between" alignItems="flex-start"><Box><Typography variant="h6">{String(item.name)}</Typography><Typography color="text.secondary">{target(item)}</Typography></Box><Chip size="small" color={item.last_test_ok ? 'success' : 'default'} label={item.last_test_ok ? 'Проверено' : 'Не проверено'} /></Stack><Stack direction="row" spacing={1} mt={2} flexWrap="wrap"><Chip size="small" label={item.channel === 'onec' ? 'Платформа 1С' : String(item.channel).toUpperCase()} /><Chip size="small" label={item.role === 'vendor' ? 'Поставщик' : 'Заказчик'} />{item.platform_version && <Chip size="small" label={String(item.platform_version)} />}</Stack>{item.user && <Typography variant="body2" mt={2}>Пользователь: {String(item.user)}</Typography>}</CardContent><CardActions sx={{ flexWrap: 'wrap' }}><Button onClick={() => api(`/connections/${item.id}/test`, { method: 'POST' }).then(refresh).catch(e => setError(e.message))}>Проверить</Button><ConnectionCredentials item={item} onSaved={refresh} onError={setError} /><Button color="error" onClick={() => remove(item)}>Удалить</Button></CardActions></Card>)}</Box>{items.length === 0 && <Alert severity="info">Подключений пока нет. Найдите базы из списка запуска 1С или добавьте подключение вручную.</Alert>}
    <Dialog open={createOpen} onClose={() => setCreateOpen(false)} fullWidth maxWidth="sm"><DialogTitle>Новое подключение</DialogTitle><DialogContent><Stack spacing={2} mt={1}><TextField label="Название" required value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} /><TextField select label="Роль" value={form.role} onChange={e => setForm({ ...form, role: e.target.value })}><MenuItem value="customer">Заказчик</MenuItem><MenuItem value="vendor">Поставщик</MenuItem></TextField><TextField select label="Канал" value={form.channel} onChange={e => setForm({ ...form, channel: e.target.value })}><MenuItem value="mcp">MCP</MenuItem><MenuItem value="web">Веб-публикация</MenuItem><MenuItem value="postgresql">PostgreSQL</MenuItem><MenuItem value="onec">Платформа 1С</MenuItem></TextField>{form.channel === 'onec' ? <><TextField label="Строка соединения 1С" value={form.connection_string} onChange={e => setForm({ ...form, connection_string: e.target.value })} helperText={'Например: Srvr="server";Ref="base";'} /><TextField label="Версия платформы" value={form.platform_version} onChange={e => setForm({ ...form, platform_version: e.target.value })} /></> : <TextField label="Адрес" value={form.url} onChange={e => setForm({ ...form, url: e.target.value })} />}</Stack></DialogContent><DialogActions><Button onClick={() => setCreateOpen(false)}>Отмена</Button><Button variant="contained" disabled={!form.name || (form.channel === 'onec' ? !form.connection_string : !form.url)} onClick={create}>Добавить</Button></DialogActions></Dialog>
    <Dialog open={discoveryOpen} onClose={() => setDiscoveryOpen(false)} fullWidth maxWidth="md"><DialogTitle>Найденные базы 1С</DialogTitle><DialogContent><Typography color="text.secondary" mb={2}>{discoverySource}</Typography><Stack spacing={1}>{discovered.map(item => <Card variant="outlined" key={`${item.folder}/${item.name}`}><CardContent><Typography variant="h6">{item.name}</Typography><Typography>{item.connection_kind === 'server' ? `${item.server} / ${item.reference}` : item.file}</Typography><Typography variant="caption">{item.folder} · платформа {item.platform_version || 'не указана'}</Typography>{item.credentials_ignored && <Alert severity="warning" sx={{ mt: 1 }}>Сохранённые параметры входа не импортируются. Введите пароль после добавления.</Alert>}</CardContent><CardActions><Button onClick={() => importInfobase(item)}>Добавить</Button></CardActions></Card>)}</Stack>{discovered.length === 0 && <Alert severity="info">Базы не найдены.</Alert>}</DialogContent><DialogActions><Button onClick={() => setDiscoveryOpen(false)}>Закрыть</Button></DialogActions></Dialog>
  </Box>;
}

function ResourcePage({ kind }: { kind: 'agents' | 'approvals' | 'runs' }) {
  const [items, setItems] = useState<RaRecord[]>([]); const [json, setJson] = useState('{\n  "name": "Codex",\n  "provider": "codex",\n  "model": "gpt-5",\n  "workers": 1,\n  "timeout_seconds": 3600,\n  "tools": ["read", "search"],\n  "enabled": true\n}'); const [secret, setSecret] = useState(''); const [error, setError] = useState('');
  const refresh = useCallback(() => api<RaRecord[]>(`/${kind}`).then(setItems).catch(e => setError(e.message)), [kind]); useEffect(() => { refresh(); }, [refresh]);
  const save = async () => { try { await api(`/${kind}`, { method: 'POST', body: JSON.stringify({ data: JSON.parse(json), secret: secret || undefined }) }); setSecret(''); refresh(); } catch (e) { setError((e as Error).message); } };
  const readonly = kind === 'approvals' || kind === 'runs';
  return <Box p={3}><Typography variant="h4" mb={2}>{({ agents: 'Профили агентов', approvals: 'Решения', runs: 'Запуски' } as const)[kind]}</Typography>{error && <Alert severity="error">{error}</Alert>}{!readonly && <Card sx={{ mb: 3 }}><CardContent><Stack spacing={2}><TextField label="Настройки JSON" multiline minRows={8} value={json} onChange={e => setJson(e.target.value)} /><TextField label="Секрет (только запись)" type="password" value={secret} onChange={e => setSecret(e.target.value)} autoComplete="new-password" /><Button variant="contained" onClick={save}>Сохранить</Button></Stack></CardContent></Card>}<Stack spacing={2}>{items.map(item => <Card key={item.id}><CardContent><Box component="pre" sx={{ whiteSpace: 'pre-wrap', overflow: 'auto', m: 0 }}>{JSON.stringify(item, (key, value) => key === 'secret_ref' ? undefined : value, 2)}</Box></CardContent><CardActions>{kind === 'approvals' && item.status === 'pending' && <><Button onClick={() => api(`/approvals/${item.id}/decision`, { method: 'POST', body: JSON.stringify({ choice: 'accept' }) }).then(refresh)}>Принять</Button><Button color="error" onClick={() => api(`/approvals/${item.id}/decision`, { method: 'POST', body: JSON.stringify({ choice: 'reject' }) }).then(refresh)}>Отклонить</Button></>}</CardActions></Card>)}</Stack></Box>;
}

export function StagePage() {
  const { projectId = '', stageId = '' } = useParams(); const [workflow, setWorkflow] = useState<Workflow>(); const [runs, setRuns] = useState<RaRecord[]>([]); const [agents, setAgents] = useState<RaRecord[]>([]); const [agentId, setAgentId] = useState(''); const [paths, setPaths] = useState('[]'); const [supplement, setSupplement] = useState(''); const [promptPreview, setPromptPreview] = useState<RaRecord>(); const [tab, setTab] = useState(0); const [error, setError] = useState('');
  const inputRef = useRef<HTMLTextAreaElement>(null);
  const refresh = useCallback(() => Promise.all([api<Workflow>(`/projects/${projectId}/workflow`), api<RaRecord[]>(`/runs?project_id=${projectId}`), api<RaRecord[]>('/agents')]).then(([w, r, a]) => { setWorkflow(w); setRuns(r.filter(x => x.stage_id === stageId)); setAgents(a); const resolved = w.stages.find(item => item.id === stageId)?.agent_profile?.id; if (resolved) setAgentId(current => current || resolved); }), [projectId, stageId]);
  useEffect(() => { refresh().catch(e => setError(e.message)); const stop = streamProject(projectId, () => refresh(), () => {}); return stop; }, [projectId, refresh]);
  const stage = workflow?.stages.find(item => item.id === stageId); const savePrompt = async () => { try { setPromptPreview(await api<RaRecord>('/prompts', { method: 'POST', body: JSON.stringify({ project_id: projectId, data: { stage_id: stageId, supplement } }) })); } catch (e) { setError((e as Error).message); } }; const run = async () => { try { await api('/runs', { method: 'POST', headers: mutationHeaders(), body: JSON.stringify({ project_id: projectId, stage_id: stageId, payload: { agent_profile_id: agentId || undefined, paths: JSON.parse(paths) } }) }); refresh(); } catch (e) { setError((e as Error).message); } };
  return <Box p={3}>{error && <Alert severity="error">{error}</Alert>}<Button component={Link} to={`/projects/${projectId}/workflow`}>← К процессу</Button><Typography variant="h4" mt={2}>{stage?.title || stageId}</Typography><Tabs value={tab} onChange={(_, value) => setTab(value)}><Tab label="Настройки" /><Tab label="Запуски и журналы" /><Tab label="Результаты" /></Tabs><Divider sx={{ mb: 3 }} />
    {tab === 0 && <Stack spacing={2} maxWidth={800}>{stage?.kind === 'agent' && <><FormControl fullWidth><InputLabel>Профиль агента</InputLabel><Select label="Профиль агента" value={agentId} onChange={e => setAgentId(e.target.value)}>{agents.filter(item => item.enabled !== false).map(item => <MenuItem key={item.id} value={String(item.id)}>{String(item.name || item.provider)} · {String(item.model)}</MenuItem>)}</Select></FormControl><TextField label="Точные входные пути (JSON)" value={paths} onChange={e => setPaths(e.target.value)} helperText="Сервер повторно проверяет разрешенные корни и отпечатки перед запуском." /><TextField label="Дополнение пользователя" multiline minRows={8} inputRef={inputRef} value={supplement} onChange={e => setSupplement(e.target.value)} helperText="Обязательные инструкции проекта и метода добавляются сервером и не изменяются." /><Button variant="outlined" onClick={savePrompt}>Сохранить новую версию промта</Button>{promptPreview && <Card variant="outlined"><CardContent><Typography variant="subtitle2">Собранный промт, версия {String(promptPreview.version)}</Typography><Box component="pre" sx={{ whiteSpace: 'pre-wrap' }}>{String(promptPreview.assembled)}</Box><Typography variant="subtitle2">Изменения</Typography><Box component="pre" sx={{ whiteSpace: 'pre-wrap' }}>{String(promptPreview.diff)}</Box></CardContent></Card>}</>}<Alert severity={stage?.ready ? 'success' : 'warning'}>{stage?.ready ? 'Этап готов к запуску' : `Блокировки: ${stage?.blockers.join(', ')}`}</Alert><Button variant="contained" disabled={!stage?.ready || (stage?.kind === 'agent' && !agentId)} onClick={run}>Запустить этап</Button></Stack>}
    {tab === 1 && <Stack spacing={2}>{runs.map(run => <Card key={run.id}><CardContent><Typography>{String(run.status)} · {String(run.started_at || 'ожидает')}</Typography><Box component="pre" sx={{ whiteSpace: 'pre-wrap', overflow: 'auto' }}>{Array.isArray(run.log_tail) ? run.log_tail.join('\n') : ''}</Box></CardContent><CardActions>{['queued', 'running'].includes(String(run.status)) && <Button color="warning" onClick={() => api(`/runs/${run.id}/cancel`, { method: 'POST' }).then(refresh)}>Отменить</Button>}{['failed', 'interrupted', 'cancelled'].includes(String(run.status)) && <Button onClick={() => api(`/runs/${run.id}/retry`, { method: 'POST', headers: mutationHeaders() }).then(refresh)}>Повторить или продолжить</Button>}</CardActions></Card>)}</Stack>}
    {tab === 2 && stage?.artifact && <iframe title={`Результат ${stage.title}`} src={`/api/v1/artifacts/${projectId}/${stage.artifact}?embed=true`} sandbox="allow-scripts" style={{ width: '100%', minHeight: 700, border: 0 }} />}
  </Box>;
}

export function App() {
  return <><GlobalStyles styles={{ '@media (prefers-reduced-motion: reduce)': { '*, *::before, *::after': { animationDuration: '0.01ms !important', animationIterationCount: '1 !important', transitionDuration: '0.01ms !important' } } }} /><Admin dataProvider={dataProvider} i18nProvider={i18nProvider} layout={WorkspaceLayout} dashboard={Home} title="1C Autoresearch" requireAuth={false} disableTelemetry>
    {resources.map(resource => <Resource key={resource} name={resource} />)}
    <CustomRoutes><Route path="/projects" element={<Home />} /><Route path="/projects/:projectId/setup" element={<SetupWizard />} /><Route path="/projects/:projectId/workflow" element={<WorkflowPage />} /><Route path="/projects/:projectId/stages/:stageId" element={<StagePage />} /><Route path="/connections" element={<ConnectionsPage />} /><Route path="/agents" element={<ResourcePage kind="agents" />} /><Route path="/approvals" element={<ResourcePage kind="approvals" />} /><Route path="/runs" element={<ResourcePage kind="runs" />} /></CustomRoutes>
  </Admin></>;
}
