import { useState } from 'react';
import { Alert, Box, Button, Checkbox, FormControl, InputLabel, MenuItem, Select, Stack, TextField, Typography } from '@mui/material';
import { api, mutationHeaders } from './api';

type Entry = { entry_id: string; filename: string; kind: string; size_bytes: number; sha256: string; role: string; semantic_key: string; status: string; duplicate_of?: string; conflict_reasons?: string[] };
type Preview = { preview_id: string; entries: Entry[]; ignored_unsupported_count: number; status_counts: Record<string, number>; total_bytes: number; declaration_fingerprint: string; draft_fingerprint: string; declaration_diff: string };

export function ExternalFolderImport({ projectId, workflowFingerprint, onComplete }: { projectId: string; workflowFingerprint: string; onComplete: () => void }) {
  const [preview, setPreview] = useState<Preview>(); const [entries, setEntries] = useState<Entry[]>([]); const [selected, setSelected] = useState<Set<string>>(new Set()); const [overrides, setOverrides] = useState<Record<string, Partial<Entry>>>({}); const [reviewed, setReviewed] = useState(false); const [cursor, setCursor] = useState(0); const [nextCursor, setNextCursor] = useState<number | null>(null); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const page = async (id: string, offset = 0) => { const value = await api<{ items: Entry[]; next_cursor: number | null }>(`/projects/${projectId}/external-folder-previews/${id}/entries?cursor=${offset}&limit=100`); setEntries(value.items); setCursor(offset); setNextCursor(value.next_cursor); };
  const choose = async (files: FileList | null) => {
    if (!files?.length) return; setBusy(true); setError('');
    try {
      const all = Array.from(files); const created = await api<{ preview_id: string; entries: { entry_id: string; filename: string }[] }>(`/projects/${projectId}/external-folder-previews`, { method: 'POST', headers: mutationHeaders(), body: JSON.stringify({ entries: all.map(file => ({ relative_path: file.webkitRelativePath, size_bytes: file.size })), expected_fingerprint: workflowFingerprint, role: 'target_cf' }) });
      const byPath = new Map(all.map(file => [file.webkitRelativePath.split('/').slice(1).join('/').normalize('NFC'), file]));
      for (const entry of created.entries) { const file = byPath.get(entry.filename); if (!file) throw new Error(`Не найден поток ${entry.filename}`); await api(`/projects/${projectId}/external-folder-previews/${created.preview_id}/entries/${entry.entry_id}`, { method: 'PUT', headers: { 'Content-Type': 'application/octet-stream', 'Idempotency-Key': crypto.randomUUID() }, body: file }); }
      const value = await api<Preview>(`/projects/${projectId}/external-folder-previews/${created.preview_id}/finalize`, { method: 'POST', headers: mutationHeaders() }); setPreview(value); setReviewed(true); setSelected(new Set(value.entries.filter(item => !['invalid', 'conflict'].includes(item.status)).map(item => item.entry_id))); await page(created.preview_id);
    } catch (caught) { setError((caught as Error).message); } finally { setBusy(false); }
  };
  const edit = (id: string, patch: Partial<Entry>) => { setOverrides(current => ({ ...current, [id]: { ...(current[id] || {}), ...patch } })); setReviewed(false); };
  const reviewDiff = async () => { if (!preview || !selected.size) return; setBusy(true); setError(''); try { const value = await api<{ diff: string }>(`/projects/${projectId}/external-folder-previews/${preview.preview_id}/declaration-diff-preview`, { method: 'POST', headers: mutationHeaders(), body: JSON.stringify({ selected_entries: Array.from(selected).map(entry_id => ({ entry_id, ...(overrides[entry_id]?.role ? { role: overrides[entry_id].role } : {}), ...(overrides[entry_id]?.semantic_key ? { semantic_key: overrides[entry_id].semantic_key } : {}) })), expected_declaration_fingerprint: preview.declaration_fingerprint }) }); setPreview(current => current ? { ...current, declaration_diff: value.diff } : current); setReviewed(true); } catch (caught) { setError((caught as Error).message); } finally { setBusy(false); } };
  const confirm = async () => {
    if (!preview || !selected.size || !reviewed || !window.confirm('Применить показанное изменение деклараций и поместить выбранные файлы в черновик?')) return; setBusy(true); setError('');
    try { const result = await api<{ status: string; missing_external_ids: string[] }>(`/projects/${projectId}/external-folder-previews/${preview.preview_id}/confirm`, { method: 'POST', headers: mutationHeaders(), body: JSON.stringify({ selected_entries: Array.from(selected).map(entry_id => ({ entry_id, ...(overrides[entry_id]?.role ? { role: overrides[entry_id].role } : {}), ...(overrides[entry_id]?.semantic_key ? { semantic_key: overrides[entry_id].semantic_key } : {}) })), expected_fingerprint: workflowFingerprint, expected_declaration_fingerprint: preview.declaration_fingerprint, expected_draft_fingerprint: preview.draft_fingerprint, confirm: true }) }); if (result.status === 'staging_incomplete') setError(`Размещение не завершено: ${result.missing_external_ids.join(', ')}`); else { setPreview(undefined); setEntries([]); onComplete(); } } catch (caught) { setError((caught as Error).message); } finally { setBusy(false); }
  };
  const cancel = async () => { if (!preview) return; await api(`/projects/${projectId}/external-folder-previews/${preview.preview_id}`, { method: 'DELETE', headers: mutationHeaders() }); setPreview(undefined); setEntries([]); };
  if (!("webkitdirectory" in document.createElement("input"))) return <Alert severity="info">Выбор папки не поддерживается браузером; используйте загрузку отдельных внешних артефактов ниже.</Alert>;
  return <Stack spacing={1.5}>{error && <Alert severity="error">{error}</Alert>}<Button component="label" disabled={busy}>Выбрать папку с EPF и ERF<input hidden type="file" multiple {...({ webkitdirectory: '' } as object)} onChange={event => void choose(event.target.files)} /></Button>{preview && <><Alert severity="info">Найдено: {preview.entries.length}; пропущено: {preview.ignored_unsupported_count}; байт: {preview.total_bytes}. После подтверждения получение исходников останется ожидающим отдельного действия.</Alert><Typography variant="caption">Страница {cursor + 1}–{cursor + entries.length}; не более 100 строк.</Typography>{entries.map(raw => { const item = { ...raw, ...(overrides[raw.entry_id] || {}) }; return <Box key={item.entry_id} sx={{ display: 'grid', gridTemplateColumns: 'auto 2fr 1fr 2fr', gap: 1, alignItems: 'center' }}><Checkbox aria-label={`Выбрать ${item.filename}`} checked={selected.has(item.entry_id)} disabled={item.status === 'invalid' || item.conflict_reasons?.includes('portable_path')} onChange={event => setSelected(current => { const next = new Set(current); event.target.checked ? next.add(item.entry_id) : next.delete(item.entry_id); setReviewed(false); return next; })} /><Box><Typography>{item.filename}</Typography><Typography variant="caption">{item.status} · {item.size_bytes} · {item.sha256}{item.duplicate_of ? ` · дубликат ${item.duplicate_of}` : ''}</Typography></Box><FormControl size="small"><InputLabel>Роль</InputLabel><Select label="Роль" value={item.role} onChange={event => edit(item.entry_id, { role: event.target.value })}>{['vendor_baseline', 'target_cf', 'next_vendor'].map(role => <MenuItem key={role} value={role}>{role}</MenuItem>)}</Select></FormControl><TextField size="small" label="Смысловой ключ" value={item.semantic_key} onChange={event => edit(item.entry_id, { semantic_key: event.target.value.normalize('NFC') })} /></Box>; })}<Stack direction="row" spacing={1}><Button disabled={cursor === 0} onClick={() => void page(preview.preview_id, Math.max(0, cursor - 100))}>Назад</Button><Button disabled={nextCursor === null} onClick={() => void page(preview.preview_id, nextCursor || 0)}>Далее</Button></Stack><Button disabled={busy || !selected.size} onClick={() => void reviewDiff()}>Пересчитать точное изменение</Button><Box component="pre" aria-label="Точное изменение деклараций" sx={{ maxHeight: 260, overflow: 'auto', whiteSpace: 'pre-wrap' }}>{preview.declaration_diff}</Box><Stack direction="row" spacing={1}><Button variant="contained" disabled={busy || !selected.size || !reviewed} onClick={() => void confirm()}>Подтвердить импорт</Button><Button color="warning" onClick={() => void cancel()}>Отменить</Button></Stack></>}</Stack>;
}
